In [1]:
import torch
import transformers
import numpy as np
import wandb
from datasets import load_dataset, Dataset
from trl import PPOTrainer, PPOConfig, AutoModelForCausalLMWithValueHead, create_reference_model
from typing import List
from tqdm import tqdm
import copy
from transformers import AutoModelForCausalLM, AutoTokenizer

from utils.prompting import *
from utils.utils import write_json, append_jsonl, normalize_answer, set_seed, load_timeqax_data
import fire
wandb.init(mode="disabled")
import pandas as pd

from peft import (
    PeftModel,
    LoraConfig,
    get_peft_model,
    prepare_model_for_kbit_training,
)

import re
import statistics

2026-01-11 17:35:30.405018: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-01-11 17:35:30.432959: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-01-11 17:35:30.432988: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-01-11 17:35:30.433002: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-01-11 17:35:30.439188: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-01-11 17:35:31.014855: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

[2026-01-11 17:35:32,451] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)

/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: cannot find -laio: No such file or directory
collect2: error: ld returned 1 exit status
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: warning: libstdc++.so.6, needed by /usr/local/cuda-11.8/lib64/libcufile.so, not found (try using -rpath or -rpath-link)
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: warning: libm.so.6, needed by /usr/local/cuda-11.8/lib64/libcufile.so, not found (try using -rpath or -rpath-link)
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::runtime_error::~runtime_error()@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `__gxx_personality_v0@CXXABI_1.3'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::ostream::tellp()@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::string::substr(unsigned long, unsigned long) const@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::string::_M_replace_aux(unsigned long, unsigned long, unsigned long, char)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `dlopen'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `typeinfo for bool@CXXABI_1.3'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::__throw_logic_error(char const*)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `VTT for std::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::locale::~locale()@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `__cxa_end_catch@CXXABI_1.3'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `VTT for std::basic_ofstream<char, std::char_traits<char> >@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `vtable for __cxxabiv1::__si_class_type_info@CXXABI_1.3'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `VTT for std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_stringbuf_init(std::_Ios_Openmode)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `operator new[](unsigned long)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::string::_M_leak_hard()@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `vtable for std::basic_ifstream<char, std::char_traits<char> >@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::string::append(char const*, unsigned long)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `typeinfo for unsigned short@CXXABI_1.3'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::string::resize(unsigned long, char)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str(std::string const&)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `typeinfo for char const*@CXXABI_1.3'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::ctype<char>::_M_widen_init() const@GLIBCXX_3.4.11'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::__throw_invalid_argument(char const*)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::_Rb_tree_decrement(std::_Rb_tree_node_base const*)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `__cxa_free_exception@CXXABI_1.3'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::ios_base::Init::~Init()@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `__cxa_pure_virtual@CXXABI_1.3'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::ostream::flush()@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `vtable for __cxxabiv1::__class_type_info@CXXABI_1.3'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `__cxa_rethrow@CXXABI_1.3'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::string::_Rep::_M_dispose(std::allocator<char> const&)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `vtable for std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::basic_fstream<char, std::char_traits<char> >::~basic_fstream()@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::string::compare(char const*) const@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::locale::locale()@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::chrono::_V2::system_clock::now()@GLIBCXX_3.4.19'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `VTT for std::basic_ifstream<char, std::char_traits<char> >@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::_Hash_bytes(void const*, unsigned long, unsigned long)@CXXABI_1.3.5'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::endl<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::ostream& std::ostream::_M_insert<long long>(long long)@GLIBCXX_3.4.9'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `typeinfo for char*@CXXABI_1.3'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::__detail::_Prime_rehash_policy::_M_need_rehash(unsigned long, unsigned long, unsigned long) const@GLIBCXX_3.4.18'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `dlclose'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::ostream& std::ostream::_M_insert<unsigned long>(unsigned long)@GLIBCXX_3.4.9'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::_Rb_tree_increment(std::_Rb_tree_node_base const*)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::ios_base::~ios_base()@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::__basic_file<char>::~__basic_file()@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `__cxa_guard_acquire@CXXABI_1.3'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::ostream& std::ostream::_M_insert<bool>(bool)@GLIBCXX_3.4.9'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `VTT for std::basic_fstream<char, std::char_traits<char> >@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `vtable for std::basic_ios<char, std::char_traits<char> >@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `vtable for std::basic_filebuf<char, std::char_traits<char> >@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `operator delete[](void*)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `vtable for std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::string::assign(char const*)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(unsigned long, char, std::allocator<char> const&)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::__detail::_List_node_base::_M_transfer(std::__detail::_List_node_base*, std::__detail::_List_node_base*)@GLIBCXX_3.4.15'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `typeinfo for std::exception@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::istream& std::istream::_M_extract<double>(double&)@GLIBCXX_3.4.9'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::basic_filebuf<char, std::char_traits<char> >::close()@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `vtable for std::basic_fstream<char, std::char_traits<char> >@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::basic_ifstream<char, std::char_traits<char> >::basic_ifstream(char const*, std::_Ios_Openmode)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::string::append(std::string const&)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `operator new(unsigned long)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `typeinfo for unsigned int@CXXABI_1.3'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::string::append(char const*)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::string::find(char, unsigned long) const@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::ostream::put(char)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `typeinfo for int@CXXABI_1.3'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::__throw_bad_alloc()@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `__cxa_thread_atexit@CXXABI_1.3.7'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::_Rb_tree_increment(std::_Rb_tree_node_base*)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::basic_ifstream<char, std::char_traits<char> >::~basic_ifstream()@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::ios_base::Init::Init()@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::__detail::_List_node_base::swap(std::__detail::_List_node_base&, std::__detail::_List_node_base&)@GLIBCXX_3.4.15'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::istream::getline(char*, long)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::basic_filebuf<char, std::char_traits<char> >::basic_filebuf()@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `VTT for std::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::cerr@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::string::find(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `vtable for std::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `typeinfo for void*@CXXABI_1.3'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::string::assign(std::string const&)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::_Rb_tree_rebalance_for_erase(std::_Rb_tree_node_base*, std::_Rb_tree_node_base&)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `typeinfo for unsigned long@CXXABI_1.3'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*)@GLIBCXX_3.4.15'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::__detail::_List_node_base::_M_unhook()@GLIBCXX_3.4.15'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)@GLIBCXX_3.4'
/home/an/anaconda3/envs/deep_learning_env_22/compiler_compat/ld: /usr/local/cuda-11.8/lib64/libcufile.so: undefined reference to `std::basic_iostream<char, std::char_traits<char> >::~basic_iostream()@GLIBCXX_3.4'

In [2]:
# training hyperparams
batch_size = 1
num_epochs = 1
# learning_rate = 5e-6
learning_rate = 2e-7
# lora hyperparams
# lora_r = 8
# lora_alpha = 16
# lora_r = 16
# lora_alpha = 32
lora_r = 64
lora_alpha = 16
lora_dropout = 0.05
lora_target_modules = ['q_proj', 'v_proj', 'k_proj', 'o_proj']
train_on_inputs = False  # if False, masks out inputs in loss
add_eos_token = False
eval_steps=200
save_steps=200
save_total_limit=10
seed=201
# debug_mode = False
debug_mode = True

# Read Data

In [48]:
train_df = pd.read_pickle("../data/rl_train/train.pkl")
train_df = train_df.reset_index().rename(columns={'index': 'id'})
train_df['user_profiles'] = train_df['s3_user_profiles']

In [50]:
train_df

,id,category,product_name,product_reviews,user_id,filtered_hist_vote_written,s1_kp,s2_kp_helpfulness_cal,s3_user_profiles,s4_helpful_kps_filtered,s5_annotated_personalized_summaries,user_profiles
0,0,Family,Connect Four,[ Most recently i have had connect four ins...,5013640,"[ I was surfing the net for some presents, ...",[Connect Four is a simple and classic two-play...,[{'kp': 'A compact travel version of Connect F...,### User Profile Summary\n\n**Personality Trai...,[A compact travel version of Connect Four is a...,Connect Four stands out as a practical and eng...,### User Profile Summary\n\n**Personality Trai...
1,1,Family,Johnson's Baby Shampoo,[ Who would have thought I would be using j...,5016911,[ I don t know how i found this magic potio...,"[Johnson's Baby Shampoo is mild and gentle, ma...",[{'kp': 'A small amount of shampoo lathers wel...,### User Profile Summary\n\n**Personality Trai...,[A small amount of shampoo lathers well and co...,If you’re on the hunt for a baby shampoo that’...,### User Profile Summary\n\n**Personality Trai...
2,2,Shopping,Tiny Computers (Shop),[ Having purchased and used a Tiny computer...,5013640,[ The btcellenet pay as you go package is a...,[Tiny Computers' customer service is extremely...,[{'kp': 'Many essential components in Tiny Com...,### User Profile Summary\n\n**Personality Trai...,[Tiny Computers covered repair costs even when...,If you’re on the lookout for a reliable PC wit...,### User Profile Summary\n\n**Personality Trai...
3,3,Entertainment,The Sun,[ Sometimes i don t really think the sun kn...,5001205,[ I think sister sister is one of the best ...,[The Sun is known for sensational headlines an...,[{'kp': 'The Sun frequently trivializes seriou...,### User Profile Summary\n\n**Personality Trai...,[The Sun frequently trivializes serious issues...,"If you’re looking for a quick, easy read that ...",### User Profile Summary\n\n**Personality Trai...
4,4,Entertainment,Channel 4 - Trigger Happy TV,[ Trigger Happy TV is so good that everytim...,5001825,[ At home with the Braithwaites follows the...,[Dom Joly plays hilarious pranks on unsuspecti...,"[{'kp': 'Dom Joly's antics, like pretending to...",### User Profile Summary\n\n**Personality Trai...,"[Dom Joly's antics, like pretending to be a pa...",If you appreciate comedy that thrives on genui...,### User Profile Summary\n\n**Personality Trai...
...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,Beauty,Original Source Tea Tree & Mint Shower Gel,[ I logged on to the Original Sources websi...,19851,"[ As a make up-aholic,I have tried just abo...",[The shower gel provides an invigorating and r...,[{'kp': 'It is not recommended for use on smal...,### User Profile: connoisseur_haggler\n\n**Per...,[It is not recommended for use on small cuts o...,If you’re after a shower gel that wakes you up...,### User Profile: connoisseur_haggler\n\n**Per...
496,496,Entertainment,Popstars,[ Pop stars is such an amazing programme. t...,5013640,[ I don t get this programme.Why would anyo...,[Popstars is a fly-on-the-wall documentary fol...,[{'kp': 'Popstars was praised for revealing th...,### User Profile Summary\n\n**Personality Trai...,[Popstars was praised for revealing the realit...,If you’re curious about the gritty realities b...,### User Profile Summary\n\n**Personality Trai...
497,497,Entertainment,ITV - Blind Date,[ Why can t we have something decent on Sat...,5013640,[ I don t get this programme.Why would anyo...,[Most contestants participate in Blind Date ma...,[{'kp': 'Blind Date is sometimes considered a ...,### User Profile Summary\n\n**Personality Trai...,[Blind Date is sometimes considered a fun and ...,"If you’re curious about ITV’s *Blind Date*, he...",### User Profile Summary\n\n**Personality Trai...
498,498,DVDs,Pretty Woman (DVD),"[ Pretty Woman, the classic tale of opposit...",5259809,[ How many cheesy american teenage films do...,[Pretty Woman is a modern Cinderella story abo...,[{'kp': 'The film is entertaining from beginni...,### User Profile Summary\n\n**Personality Trai...,[The film is entertaining from beginning to en...,“Pretty Woman” on DVD offers an entertaining r...,### User Profile Summary\n\n**Personality Trai...
499,499,Books,Bridget Jones's Diary - Helen Fielding,[ Damn sexy.Literary calories: far too many...,5241315,[ *~*~*~*~*~*~*~*~*~*~*The Blur*~*~*~*~*~*~...,[Bridget Jones's Diary is a genuinely funny an...,[{'kp': 'Bridget's obsession with weight and s...,### User Profile Summary\n\n**Personality Trai...,[Bridget's obsession with weight and self-impr...,Helen Fielding’s *Bridget Jones’s Diary* offer...,### User Profile Summary\n\n**Personality Trai...

In [5]:
train_data = train_df

# Setup

## Policy Model

In [6]:
TEMPLATE = get_prompt("helpfulsumm_cot_helpful_pos")

In [7]:
device_map = "auto"
world_size = int(os.environ.get("WORLD_SIZE", 1))
ddp = world_size != 1
if ddp:
    device_map = {"": int(os.environ.get("LOCAL_RANK") or 0)}

In [8]:
base_model = "hugging-quants/Meta-Llama-3.1-8B-Instruct-GPTQ-INT4"
source_path = '../models/stage_1_helpfulsumm_ft/checkpoint-800'

In [9]:
output_dir = f'../models/stage_2_helpfulsumm_rl_2/'

In [10]:
os.makedirs(output_dir, exist_ok=True)
set_seed(seed=seed)

In [11]:
policy_model = AutoModelForCausalLM.from_pretrained(
    source_path,
    device_map='auto',
    trust_remote_code=False,
    revision="main"
)

/mnt/c/Users/antan/Desktop/PHD READING/Product_Question_Answering/JustiLM_Question_based_Summarization/AutoGPTQ/auto_gptq/nn_modules/triton_utils/kernels.py:411: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  def forward(ctx, input, qweight, scales, qzeros, g_idx, bits, maxq):
/mnt/c/Users/antan/Desktop/PHD READING/Product_Question_Answering/JustiLM_Question_based_Summarization/AutoGPTQ/auto_gptq/nn_modules/triton_utils/kernels.py:419: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(ctx, grad_output):
/mnt/c/Users/antan/Desktop/PHD READING/Product_Question_Answering/JustiLM_Question_based_Summarization/AutoGPTQ/auto_gptq/nn_modules/triton_utils/kernels.py:461: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd(cast_inputs=torch.float16)
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/modeling_utils.py:4713: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead
  warnings.warn(

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [12]:
from auto_gptq import exllama_set_max_input_length
policy_model = exllama_set_max_input_length(policy_model, max_input_length=65536)

In [13]:
policy_model

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(128256, 4096)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaSdpaAttention(
          (rotary_emb): LlamaRotaryEmbedding()
          (k_proj): lora.QuantLinear(
            (base_layer): QuantLinear()
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.05, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=4096, out_features=16, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=16, out_features=1024, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (quant_linear_module): QuantLinear()
          )
          (o_proj): lora.QuantLinear(
            (base_layer): QuantLinear()
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.05, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=4096, out_features=16, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=16, out_features=4096, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (quant_linear_module): QuantLinear()
          )
          (q_proj): lora.QuantLinear(
            (base_layer): QuantLinear()
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.05, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=4096, out_features=16, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=16, out_features=4096, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (quant_linear_module): QuantLinear()
          )
          (v_proj): lora.QuantLinear(
            (base_layer): QuantLinear()
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.05, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=4096, out_features=16, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=16, out_features=1024, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (quant_linear_module): QuantLinear()
          )
        )
        (mlp): LlamaMLP(
          (act_fn): SiLU()
          (down_proj): QuantLinear()
          (gate_proj): QuantLinear()
          (up_proj): QuantLinear()
        )
        (input_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
        (post_attention_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
      )
    )
    (norm): LlamaRMSNorm((4096,), eps=1e-05)
    (rotary_emb): LlamaRotaryEmbedding()
  )
  (lm_head): Linear(in_features=4096, out_features=128256, bias=False)
)

In [14]:
peft_config = LoraConfig(
    r=lora_r,
    lora_alpha=lora_alpha,
    target_modules=lora_target_modules,
    lora_dropout=lora_dropout,
    bias="none",
    task_type="CAUSAL_LM",
)

In [15]:
ref_model = create_reference_model(policy_model)
ref_model = AutoModelForCausalLMWithValueHead.from_pretrained(ref_model)

In [16]:
policy_model = get_peft_model(policy_model, peft_config)
policy_model = AutoModelForCausalLMWithValueHead.from_pretrained(policy_model)

In [17]:
tokenizer = transformers.AutoTokenizer.from_pretrained(
    base_model,
    padding_side="right",
)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.pad_token_id = (
    tokenizer.eos_token_id
)
tokenizer.add_prefix_space = False

In [18]:
def tokenize(prompt):
    result = tokenizer(
        prompt
    )
    result["labels"] = result["input_ids"].copy()

    return result

In [19]:
def generate_and_tokenize_prompt(data_point, gen=False, eval=False):
    product_name = data_point['product_name']
    product_reviews = data_point['product_reviews']

    hist_vote_written = data_point['filtered_hist_vote_written']
    
    query = TEMPLATE.format(product_name = product_name, product_reviews = product_reviews, 
                            hist_vote_written = hist_vote_written)
    
    if eval:
        msg = [{"role": "user", "content": query}, {"role": "assistant", "content": response}]
        formatted_prompt =  tokenizer.apply_chat_template(msg, tokenize=False, add_generation_prompt=False)
        tokenized_full_prompt = tokenize(formatted_prompt)
    elif gen:
        msg = [{"role": "user", "content": query}]
        formatted_prompt =  tokenizer.apply_chat_template(msg, tokenize=False, add_generation_prompt=True)
        tokenized_full_prompt = tokenize(formatted_prompt)
    else:
        msg = [{"role": "user", "content": query}, {"role": "assistant", "content": response}]
        formatted_prompt =  tokenizer.apply_chat_template(msg, tokenize=False, add_generation_prompt=False)
        tokenized_full_prompt = tokenize(formatted_prompt)

    if not train_on_inputs:
        user_msg = [{"role": "user", "content": query}]
        user_prompt = tokenizer.apply_chat_template(user_msg, tokenize=False, add_generation_prompt=False)
        tokenized_user_prompt = tokenize(user_prompt)
        user_prompt_len = len(tokenized_user_prompt["input_ids"])
        if add_eos_token:
            user_prompt_len -= 1
        tokenized_full_prompt["labels"] = [-100] * user_prompt_len + tokenized_full_prompt["labels"][user_prompt_len:]

    tokenized_full_prompt['id'] = int(data_point['id'])
    
    return tokenized_full_prompt

def generate_and_tokenize_prompt_gen(data_point):
    return generate_and_tokenize_prompt(data_point, gen=True)

def process_query_tensor(qt):
    i = qt.tolist().index(128000)
    return qt[i:]

def save_check_point():
    pass

def get_step_logs(stats, batch, rewards, step_i):
    logs = {}
    logs['step'] = step_i
    rewards = torch.stack(rewards)
    for k, v in stats.items():
        if not isinstance(v, np.ndarray):
            logs[k] = v
    logs["env/reward_mean"] = torch.mean(rewards).item()	# torch.mean(rewards).cpu().numpy().item()
    logs["env/reward_std"] = torch.std(rewards).item()		# torch.std(rewards).cpu().numpy().item()
    logs["env/reward_dist"] = rewards.tolist()	# rewards.cpu().numpy()
    return logs

def get_text_logs(pred, ans, epoch, step_i, idx_b):
    logs = []
    for p, a, idx in zip(pred, ans, idx_b):
        d = {'epoch': epoch, 'step': step_i, 'id': idx, 'output': p}
        logs.append(d)
        idx += 1
    return logs

In [20]:
train_data

,id,category,product_name,product_reviews,user_id,filtered_hist_vote_written,s1_kp,s2_kp_helpfulness_cal,s3_user_profiles,s4_helpful_kps_filtered,s5_annotated_personalized_summaries
0,0,Family,Connect Four,[ Most recently i have had connect four ins...,5013640,"[ I was surfing the net for some presents, ...",[Connect Four is a simple and classic two-play...,[{'kp': 'A compact travel version of Connect F...,### User Profile Summary\n\n**Personality Trai...,[A compact travel version of Connect Four is a...,Connect Four stands out as a practical and eng...
1,1,Family,Johnson's Baby Shampoo,[ Who would have thought I would be using j...,5016911,[ I don t know how i found this magic potio...,"[Johnson's Baby Shampoo is mild and gentle, ma...",[{'kp': 'A small amount of shampoo lathers wel...,### User Profile Summary\n\n**Personality Trai...,[A small amount of shampoo lathers well and co...,If you’re on the hunt for a baby shampoo that’...
2,2,Shopping,Tiny Computers (Shop),[ Having purchased and used a Tiny computer...,5013640,[ The btcellenet pay as you go package is a...,[Tiny Computers' customer service is extremely...,[{'kp': 'Many essential components in Tiny Com...,### User Profile Summary\n\n**Personality Trai...,[Tiny Computers covered repair costs even when...,If you’re on the lookout for a reliable PC wit...
3,3,Entertainment,The Sun,[ Sometimes i don t really think the sun kn...,5001205,[ I think sister sister is one of the best ...,[The Sun is known for sensational headlines an...,[{'kp': 'The Sun frequently trivializes seriou...,### User Profile Summary\n\n**Personality Trai...,[The Sun frequently trivializes serious issues...,"If you’re looking for a quick, easy read that ..."
4,4,Entertainment,Channel 4 - Trigger Happy TV,[ Trigger Happy TV is so good that everytim...,5001825,[ At home with the Braithwaites follows the...,[Dom Joly plays hilarious pranks on unsuspecti...,"[{'kp': 'Dom Joly's antics, like pretending to...",### User Profile Summary\n\n**Personality Trai...,"[Dom Joly's antics, like pretending to be a pa...",If you appreciate comedy that thrives on genui...
...,...,...,...,...,...,...,...,...,...,...,...
495,495,Beauty,Original Source Tea Tree & Mint Shower Gel,[ I logged on to the Original Sources websi...,19851,"[ As a make up-aholic,I have tried just abo...",[The shower gel provides an invigorating and r...,[{'kp': 'It is not recommended for use on smal...,### User Profile: connoisseur_haggler\n\n**Per...,[It is not recommended for use on small cuts o...,If you’re after a shower gel that wakes you up...
496,496,Entertainment,Popstars,[ Pop stars is such an amazing programme. t...,5013640,[ I don t get this programme.Why would anyo...,[Popstars is a fly-on-the-wall documentary fol...,[{'kp': 'Popstars was praised for revealing th...,### User Profile Summary\n\n**Personality Trai...,[Popstars was praised for revealing the realit...,If you’re curious about the gritty realities b...
497,497,Entertainment,ITV - Blind Date,[ Why can t we have something decent on Sat...,5013640,[ I don t get this programme.Why would anyo...,[Most contestants participate in Blind Date ma...,[{'kp': 'Blind Date is sometimes considered a ...,### User Profile Summary\n\n**Personality Trai...,[Blind Date is sometimes considered a fun and ...,"If you’re curious about ITV’s *Blind Date*, he..."
498,498,DVDs,Pretty Woman (DVD),"[ Pretty Woman, the classic tale of opposit...",5259809,[ How many cheesy american teenage films do...,[Pretty Woman is a modern Cinderella story abo...,[{'kp': 'The film is entertaining from beginni...,### User Profile Summary\n\n**Personality Trai...,[The film is entertaining from beginning to en...,“Pretty Woman” on DVD offers an entertaining r...
499,499,Books,Bridget Jones's Diary - Helen Fielding,[ Damn sexy.Literary calories: far too many...,5241315,[ *~*~*~*~*~*~*~*~*~*~*The Blur*~*~*~*~*~*~...,[Bridget Jones's Diary is a genuinely funny an...,[{'kp': 'Bridget's obsession with weight and s...,### User Profile Summary\n\n**Personality Trai...,[Bridget's obsession with weight and self-impr...,Helen Fielding’s *Bridget Jones’s Diary* offer...

In [21]:
print('convert data ...')
train_data = Dataset.from_pandas(train_data).map(generate_and_tokenize_prompt_gen)
train_data = train_data.select_columns(['input_ids', 'attention_mask', 'labels', 'id'])

convert data ...

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

In [22]:
if not ddp and torch.cuda.device_count() > 1:
    # keeps Trainer from trying its own DataParallelism when more than 1 gpu is available
    ref_model.is_parallelizable = True
    ref_model.model_parallel = True
    policy_model.is_parallelizable = True
    policy_model.model_parallel = True

In [23]:
micro_batch_size = 1
_batch_size = micro_batch_size
gradient_accumulation_steps = 1
_batch_size = micro_batch_size
_lr = learning_rate
config = PPOConfig(
    reward_model=None,
    kl_penalty="kl",
    batch_size=2,
    mini_batch_size=1,
    gradient_accumulation_steps=gradient_accumulation_steps,
    ppo_epochs=num_epochs,
    learning_rate=_lr,
    remove_unused_columns=False,
    seed=42,
)

trainer = PPOTrainer(
    config=config,
    tokenizer=tokenizer,
    model=policy_model,
    ref_model=ref_model,
    dataset=train_data,
    data_collator=transformers.DataCollatorForSeq2Seq(
            tokenizer,
            pad_to_multiple_of=8,
            return_tensors="pt",
            padding=True,
        ),
)

generation_kwargs = {
    "min_length": -1,
    "top_k": 0.0,
    "top_p": 1.0,
    "do_sample": False,
    "repetition_penalty": 1.0,
    "pad_token_id": tokenizer.eos_token_id,
    "max_new_tokens": 1000,
#     "max_new_tokens": 15,
    "eos_token_id": tokenizer.eos_token_id,
}

## Claim Extraction

In [24]:
from openai import OpenAI
client = OpenAI(
    api_key = api_key
)

model="gpt-4.1"
prompt = "Once upon a time"

In [25]:
def get_completion(prompt, model=model):
    messages = [{"role": "user", "content": prompt}]
    ct = 0
    while ct < 2:
        try:
            response = client.chat.completions.create(
                model=model,
                messages=messages,
                max_tokens=1000,
                temperature=0, # this is the degree of randomness of the model's output
            )
            return response.choices[0].message.content
            break
        except Exception as e:
            print(e)
            ct += 1
        
    return response.choices[0].message.content

In [26]:
base_prompt = get_prompt("summary_kp_extraction")

In [27]:
def claim_extraction_from_summary(text):
    claim_split_prompt = base_prompt %(text)
    attempt = 0
    claim_split_response = None
    while attempt < 3 and claim_split_response == None:
        claim_split_response = get_completion(claim_split_prompt, model)
        attempt += 1
        
    if claim_split_response != None:
        claim_split_response = claim_split_response.replace("`", "").replace("json", "")
        generated_summary_kps = ast.literal_eval(claim_split_response)
    else:
        generated_summary_kps = []
    return generated_summary_kps

## KP Helpfulness Reward Model

In [28]:
import math, numpy as np, torch, torch.nn as nn, torch.nn.functional as F
from transformers import AutoTokenizer, AutoModel, AutoConfig, Trainer, TrainingArguments
from datasets import Dataset
from scipy.stats import pearsonr, spearmanr
import ast

In [29]:
class CrossEncoderRegressor(nn.Module):
    def __init__(self, model_name):
        super().__init__()
        self.device = torch.device("cpu")  # <<< force CPU
        
        self.config = AutoConfig.from_pretrained(model_name)
        self.backbone = AutoModel.from_pretrained(model_name, config=self.config, low_cpu_mem_usage=True)
        self.dropout = nn.Dropout(self.config.hidden_dropout_prob if hasattr(self.config, "hidden_dropout_prob") else 0.1)
        self.head = nn.Linear(self.config.hidden_size, 1)  # scalar
        
         # Ensure whole module is on CPU (paranoia; everything should already be)
        self.to(self.device)
        self.eval()  # inference by default for a reward model
        
    def forward(self, input_ids, attention_mask, token_type_ids=None, labels=None):
        if input_ids.device.type != "cpu":
            input_ids = input_ids.to("cpu")
        if attention_mask is not None and attention_mask.device.type != "cpu":
            attention_mask = attention_mask.to("cpu")
        if token_type_ids is not None and token_type_ids.device.type != "cpu":
            token_type_ids = token_type_ids.to("cpu")

        out = self.backbone(
            input_ids=input_ids,
            attention_mask=attention_mask,
            token_type_ids=token_type_ids
        )
        
        # pool: prefer CLS token; if pooler exists (BERT), you can use pooler_output
        if hasattr(out, "pooler_output") and out.pooler_output is not None:
            pooled = out.pooler_output
        else:
            pooled = out.last_hidden_state[:, 0, :]  # CLS
        x = self.dropout(pooled)
        raw = self.head(x).squeeze(-1)             # shape [B]
        pred01 = torch.sigmoid(raw)                 # in [0,1]
        pred = pred01 * 4.0 + 1.0                  # bound to [1,5]
        outputs = {"logits": pred.unsqueeze(-1)}   # Trainer expects "logits"
        if labels is not None:
            labels = labels.to(pred.dtype)
            loss = F.mse_loss(pred, labels)
            outputs["loss"] = loss
        return outputs
    
reward_model = CrossEncoderRegressor("microsoft/deberta-v2-xlarge")
reward_model.load_state_dict(torch.load('../models/stage_2_helpful_opinion_reward_deberta_ft/model_3_epoch_good.pth', map_location=torch.device("cpu")))

/tmp/ipykernel_8379/386505670.py:46: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  reward_model.load_state_dict(torch.load('../models/stage_2_helpful_opinion_reward_deberta_ft/model_3_epoch_good.pth', map_location=torch.device("cpu")))

In [30]:
reward_model_checkpoint = "microsoft/deberta-v2-xlarge"   # swap to "bert-base-uncased" if you prefer BERT
rewrd_tokenizer = AutoTokenizer.from_pretrained(reward_model_checkpoint, use_fast=True)

/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

In [31]:
def tokenize_function(examples):
    out = rewrd_tokenizer(
        examples["kp"],
        examples["history_text"],
        padding="max_length", 
        truncation=True,
        max_length=MAX_LEN,
    )
    out["user_id"] = examples["user_id"]
    return out

In [32]:
from rouge_score import rouge_scorer
scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)

def calculate_rouge_score(row):
    rouge1_scores, rouge2_scores, rougel_scores = [], [], []
    for rev in row['filtered_hist_vote_written']:
        scores = scorer.score(row['key_point'], rev)
        rouge1_scores += [scores['rouge1'].fmeasure]
        rouge2_scores += [scores['rouge2'].fmeasure]
        rougel_scores += [scores['rougeL'].fmeasure]
        
    row['rouge1_scores'] = rouge1_scores
    row['rouge2_scores'] = rouge2_scores
    row['rougel_scores'] = rougel_scores

    return row

In [33]:
def filter_hist_vote_written(row):
    my_df = row[['filtered_hist_vote_written', 'rouge1_scores', 'rouge2_scores', 'rougel_scores']].to_frame().T
    my_df = my_df.explode(['filtered_hist_vote_written', 'rouge1_scores', 'rouge2_scores', 'rougel_scores'])
    my_df = my_df.sort_values(by=['rougel_scores', 'rouge2_scores', 'rouge1_scores'], ascending=False)
    row['sorted_hist_vote_written'] = my_df['filtered_hist_vote_written'].tolist()
    return row

In [34]:
def join_history(reviews):
    # Use tokenizer-specific separator; helps the encoder segment reviews
    sep = rewrd_tokenizer.sep_token if rewrd_tokenizer.sep_token is not None else " "
    return f" {sep} ".join([r.strip() for r in reviews])

## Persona Consistency Reward Model

In [55]:
from openai import OpenAI
client = OpenAI(
    api_key = api_key
)
persona_reward_model="gpt-3.5-turbo"

In [56]:
def get_scoring_completion(prompt, model=persona_reward_model):
    ct = 0
    all_responses = None
    while ct < 2:
        try:
            if ct == 0:
                _response = client.chat.completions.create(
                    model=model,
                    messages=[{"role": "system", "content": prompt}],
                    temperature=2,
                    max_tokens=150,
                    top_p=1,
                    frequency_penalty=0,
                    presence_penalty=0,
                    stop=None,
                    n=5
                )

                all_responses = [_response.choices[i].message.content for i in
                                 range(len(_response.choices))]
            else:
                _response = personal_client.chat.completions.create(
                    model=model,
                    messages=[{"role": "system", "content": prompt}],
                    temperature=2,
                    max_tokens=150,
                    top_p=1,
                    frequency_penalty=0,
                    presence_penalty=0,
                    stop=None,
                    n=5
                )
                all_responses = [_response.choices[i].message.content for i in
                                 range(len(_response.choices))]
        
            break
        except Exception as e:
            print(e)
                
    return all_responses

In [57]:
# BEST (OK) BEST
persona_reward_prompt = get_prompt("persona_alignment_reward_scoring")

In [58]:
def calculate_persona_reward(df):
    product_name = df.iloc[0]['product_name']
    ext = re.findall(r"# Personalized Summary:\n*((?:.+\n*)+)", df.iloc[0]['generated_personalized_summaries'])
    if len(ext) > 0:
        generated_personalized_summary = ext[0]
    else:
        generated_personalized_summary = df.iloc[0]['generated_personalized_summaries']
    hist_vote_written = [rev.strip() for rev in df.iloc[0]['hist_vote_written']]
    user_profile = df.iloc[0]['user_profiles']
    
    prompt = persona_reward_prompt % (product_name, generated_personalized_summary, user_profile)
    
    all_responses = get_scoring_completion(prompt)
    
    rating_extractions =  [[int(rating) for rating in re.findall(r'[0-9]+', ext_response)[:6] if 1 <= int(rating) <= 5] for ext_response in all_responses]
    rating_extractions = [run for run in rating_extractions if len(run) == 6]
    
    if len(rating_extractions) == 0:
        personal_utterance_reward = 1
    else:
        personal_utterance_reward = statistics.mean([statistics.mean(run) for run in rating_extractions])
    
    return personal_utterance_reward, rating_extractions, all_responses

# Train

## Setup

In [59]:
def calculate_kp_helpfulness_score(entry_id, generated_summary, generated_summary_kps):
    kp_df = pd.DataFrame({'id': [entry_id for i in range(len(generated_summary_kps))] , 'key_point': generated_summary_kps})
    kp_df['generated_personalized_summaries'] = generated_summary
    kp_df = kp_df.merge(train_df[['id', 'product_name', 'category', 'user_id']])
    
    kp_df = kp_df.merge(train_df)
    kp_df = kp_df.apply(calculate_rouge_score, axis=1)
    kp_df = kp_df.apply(filter_hist_vote_written, axis=1)
    kp_df = kp_df[['id', 'category', 'product_name', 'user_id', 'user_profiles', 'key_point', 'sorted_hist_vote_written']].\
        rename(columns={'sorted_hist_vote_written': 'hist_vote_written'})
    kp_df['history_text'] = kp_df['hist_vote_written'].apply(join_history)
    kp_df = kp_df.rename(columns={'key_point': 'kp', 'user_id': 'user_id'})
    
    kp_data = Dataset.from_pandas(kp_df)
    tokenized_kp_data = kp_data.map(tokenize_function, batched=True, remove_columns=kp_data.column_names)
    tokenized_kp_data.set_format("torch")
    from torch.utils.data import DataLoader
    eval_dataloader = DataLoader(tokenized_kp_data, batch_size=2)
    
    reward_model.eval()
    output = []
    for reward_batch in eval_dataloader:
    #     batch_inputs, batch_masks, _ = tuple(b.to(device) for b in batch)
        batch_inputs = reward_batch['input_ids'].to("cpu")
        batch_masks = reward_batch['attention_mask'].to("cpu")
        with torch.no_grad():
            output += reward_model(batch_inputs, batch_masks)["logits"].view(1,-1).tolist()[0]
    
    kp_df['predicted_kp_helpfulness'] = output
    
    return kp_df

In [60]:
def save_rl_data(root_path, kp_df):
    os.makedirs(root_path, exist_ok=True)
    category = kp_df['category'].iloc[0]
    user_id = kp_df['user_id'].iloc[0]
    idx = str(kp_df['id'].iloc[0])
    kp_df.to_pickle(root_path + f"/{category}_{idx}_{user_id}.pkl")

## Train

In [61]:
from datasets.utils.logging import disable_progress_bar
disable_progress_bar()

In [62]:
epochs = num_epochs
print("TOTAL EPOCHS: ", num_epochs)
step_i = 0

TOTAL EPOCHS:  1

In [63]:
MAX_LEN = 512

In [64]:
root_path = output_dir + "rl_output/"

In [65]:
responses = []

In [66]:
import gc
import torch

In [132]:
for epoch in tqdm(range(epochs), "epoch:", ncols=100):
    for batch in tqdm(trainer.dataloader, desc=f"Batch (Epoch {epoch + 1})", leave=False, ncols=100):
        query_tensors = batch["input_ids"]
        input_tensors_b = [process_query_tensor(qt) for qt in query_tensors]
        response_tensors_b = []
        for input_tensors in input_tensors_b:
            response_tensors = trainer.generate([input_tensors], return_prompt=False, **generation_kwargs)
            response_tensors_b += response_tensors
        
        response_b = [tokenizer.decode(rt, skip_special_tokens=True).strip() for rt in response_tensors_b]
        responses += response_b
        batch['response'] = response_b
        id_b = batch['id'].tolist()

        print(f'step-{step_i} >>>')
        
        reward_b = []
        for summ in response_b:
            if len(summ.strip()) > 0:
                ############################### KP HELPFULNESS REWARD
                generated_summary_kps = claim_extraction_from_summary(summ)
                if len(generated_summary_kps) > 0:
                    kp_df = calculate_kp_helpfulness_score(id_b[0], summ, generated_summary_kps)
                    kp_helpfulness_reward = kp_df['predicted_kp_helpfulness'].mean()
                    kp_df['generated_personalized_summaries'] = summ
                

                    ############################### PERSONA CONSISTENCY REWARD
                    personal_utterance_reward, rating_extractions, all_responses = calculate_persona_reward(kp_df)

                    ############################### SAVE
                    kp_df['kp_helpfulness_reward'] = kp_helpfulness_reward
                    kp_df['personal_utterance_rating_extractions'] = [rating_extractions for i in range(len(kp_df))]
                    kp_df['personal_utterance_all_responses'] = [all_responses for i in range(len(kp_df))]
                    kp_df['personal_utterance_reward'] = personal_utterance_reward
                    save_rl_data(root_path, kp_df)
                    
                else:
                    print("############################ NOTE ############################")
                    kp_df = 123
                    kp_helpfulness_reward = 0
                    personal_utterance_reward, rating_extractions, all_responses = calculate_persona_reward(kp_df)

                ############################### COMBINE
                final_reward = kp_helpfulness_reward * 0.5 + personal_utterance_reward * 0.5
                reward_b += [torch.tensor(final_reward)]
            else:
                reward_b += [torch.tensor(0)]
        
        stats = trainer.step([qt for qt in query_tensors], [rt for rt in response_tensors_b], reward_b)

        step_logs = get_step_logs(stats, batch, reward_b, step_i)
        append_jsonl(step_logs, os.path.join(output_dir, 'logs.jsonl'))

        if step_i % 50 == 0:
            checkpoint_folder_name = f"step-{step_i}"
            checkpoint_dir = os.path.join(output_dir, checkpoint_folder_name)
            os.makedirs(checkpoint_dir)
            trainer.model.save_pretrained(checkpoint_dir, safe_serialization=False)
            step_stats = {k: v.tolist() if isinstance(v, np.ndarray) else v for k, v in stats.items()}
            write_json(step_stats, os.path.join(checkpoint_dir, 'reward_stats.json'))

        step_i += 1
        del query_tensors, input_tensors_b, response_tensors_b, response_tensors
        del kp_helpfulness_reward
        del personal_utterance_reward, rating_extractions, all_responses
        del reward_b, kp_df
        gc.collect()
        torch.cuda.empty_cache()  # harmless; can help reduce fragmentation

    if step_i > 150000:
        break

epoch::   0%|                                                                 | 0/1 [00:00<?, ?it/s]
Batch (Epoch 1):   0%|                                                      | 0/250 [00:00<?, ?it/s]You're using a PreTrainedTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-0 >>>

/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/peft/utils/save_and_load.py:154: UserWarning: Could not find a config file in ./model/Meta-Llama-3.1-8B-Instruct-GPTQ-INT4 - will assume that the vocabulary was not modified.
  warnings.warn(

>>> write to saved/lora_llama318ft_policy_r8_lr2e-07_b1_sd201_general_sample_500_new_filtered_full_rewards_great/step-0/reward_stats.json

Batch (Epoch 1):   0%|▏                                           | 1/250 [01:21<5:37:39, 81.36s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-1 >>>

Batch (Epoch 1):   1%|▎                                          | 2/250 [03:22<7:11:55, 104.50s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-2 >>>

Batch (Epoch 1):   1%|▌                                           | 3/250 [04:30<6:02:00, 87.94s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-3 >>>

Batch (Epoch 1):   2%|▋                                           | 4/250 [06:21<6:38:33, 97.21s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-4 >>>

Batch (Epoch 1):   2%|▉                                           | 5/250 [07:31<5:56:56, 87.41s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-5 >>>

Batch (Epoch 1):   2%|█                                           | 6/250 [09:26<6:33:55, 96.87s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-6 >>>

Batch (Epoch 1):   3%|█▏                                          | 7/250 [10:49<6:13:29, 92.22s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-7 >>>

Batch (Epoch 1):   3%|█▍                                         | 8/250 [12:46<6:43:52, 100.13s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-8 >>>

Batch (Epoch 1):   4%|█▌                                          | 9/250 [14:19<6:32:23, 97.69s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-9 >>>

Batch (Epoch 1):   4%|█▋                                         | 10/250 [16:02<6:38:06, 99.53s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-10 >>>

Batch (Epoch 1):   4%|█▉                                         | 11/250 [17:29<6:21:18, 95.73s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-11 >>>

Batch (Epoch 1):   5%|██                                         | 12/250 [19:09<6:24:09, 96.85s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-12 >>>

Batch (Epoch 1):   5%|██▏                                        | 13/250 [20:24<5:56:14, 90.19s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-13 >>>

Batch (Epoch 1):   6%|██▍                                        | 14/250 [22:22<6:28:45, 98.84s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-14 >>>

Batch (Epoch 1):   6%|██▌                                       | 15/250 [24:22<6:51:48, 105.14s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-15 >>>

Batch (Epoch 1):   6%|██▊                                        | 16/250 [25:50<6:29:51, 99.96s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-16 >>>

Batch (Epoch 1):   7%|██▊                                       | 17/250 [27:50<6:51:59, 106.09s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-17 >>>

Batch (Epoch 1):   7%|███                                       | 18/250 [29:54<7:10:45, 111.40s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-18 >>>

Batch (Epoch 1):   8%|███▏                                      | 19/250 [31:11<6:29:25, 101.15s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-19 >>>

Batch (Epoch 1):   8%|███▎                                      | 20/250 [32:55<6:30:49, 101.95s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-20 >>>

Batch (Epoch 1):   8%|███▌                                      | 21/250 [34:55<6:49:56, 107.41s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-21 >>>

Batch (Epoch 1):   9%|███▋                                      | 22/250 [36:49<6:55:06, 109.24s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-22 >>>

Batch (Epoch 1):   9%|███▊                                      | 23/250 [38:49<7:05:36, 112.50s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-23 >>>

Batch (Epoch 1):  10%|████                                      | 24/250 [40:57<7:21:34, 117.23s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-24 >>>

Batch (Epoch 1):  10%|████▏                                     | 25/250 [42:31<6:53:19, 110.22s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-25 >>>

Batch (Epoch 1):  10%|████▎                                     | 26/250 [44:04<6:32:35, 105.16s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-26 >>>

Batch (Epoch 1):  11%|████▌                                     | 27/250 [46:08<6:51:02, 110.60s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-27 >>>

Batch (Epoch 1):  11%|████▋                                     | 28/250 [47:43<6:32:22, 106.05s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-28 >>>

Batch (Epoch 1):  12%|████▉                                      | 29/250 [48:21<5:15:16, 85.59s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-29 >>>

Batch (Epoch 1):  12%|█████▏                                     | 30/250 [50:20<5:50:37, 95.63s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-30 >>>

Batch (Epoch 1):  12%|█████▎                                     | 31/250 [51:33<5:24:13, 88.83s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-31 >>>

Batch (Epoch 1):  13%|█████▍                                    | 32/250 [53:39<6:03:30, 100.05s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-32 >>>

Batch (Epoch 1):  13%|█████▌                                    | 33/250 [55:40<6:23:47, 106.12s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-33 >>>

Batch (Epoch 1):  14%|█████▋                                    | 34/250 [57:42<6:39:32, 110.98s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-34 >>>

/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/trl/trainer/ppo_trainer.py:1279: UserWarning: KL divergence is starting to become negative: -1.12 - this might be a precursor for failed training. sometimes this happens because the generation kwargs are not correctly set. Please make sure that the generation kwargs are set correctly, or review your training hyperparameters.
  warnings.warn(

Batch (Epoch 1):  14%|█████▉                                    | 35/250 [59:33<6:38:01, 111.08s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-35 >>>

Batch (Epoch 1):  14%|█████▊                                  | 36/250 [1:01:16<6:27:07, 108.54s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-36 >>>

Batch (Epoch 1):  15%|█████▉                                  | 37/250 [1:03:11<6:32:29, 110.56s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-37 >>>

Batch (Epoch 1):  15%|██████                                  | 38/250 [1:05:16<6:46:02, 114.92s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-38 >>>

Batch (Epoch 1):  16%|██████▏                                 | 39/250 [1:06:31<6:02:13, 103.00s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-39 >>>

Batch (Epoch 1):  16%|██████▍                                 | 40/250 [1:08:43<6:30:28, 111.57s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-40 >>>

Batch (Epoch 1):  16%|██████▌                                 | 41/250 [1:10:44<6:38:19, 114.35s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-41 >>>

Batch (Epoch 1):  17%|██████▋                                 | 42/250 [1:12:10<6:07:14, 105.94s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-42 >>>

Batch (Epoch 1):  17%|██████▉                                 | 43/250 [1:14:07<6:17:12, 109.34s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-43 >>>

Batch (Epoch 1):  18%|███████                                 | 44/250 [1:15:44<6:02:05, 105.46s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-44 >>>

Batch (Epoch 1):  18%|███████▏                                | 45/250 [1:17:11<5:41:42, 100.01s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-45 >>>

Batch (Epoch 1):  18%|███████▌                                 | 46/250 [1:17:53<4:41:08, 82.69s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-46 >>>

Batch (Epoch 1):  19%|███████▋                                 | 47/250 [1:19:51<5:15:17, 93.19s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-47 >>>

Batch (Epoch 1):  19%|███████▊                                 | 48/250 [1:21:35<5:24:35, 96.41s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-48 >>>

Batch (Epoch 1):  20%|████████                                 | 49/250 [1:23:00<5:11:39, 93.03s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-49 >>>

Batch (Epoch 1):  20%|████████▏                                | 50/250 [1:24:49<5:25:47, 97.74s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-50 >>>

/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/peft/utils/save_and_load.py:154: UserWarning: Could not find a config file in ./model/Meta-Llama-3.1-8B-Instruct-GPTQ-INT4 - will assume that the vocabulary was not modified.
  warnings.warn(

>>> write to saved/lora_llama318ft_policy_r8_lr2e-07_b1_sd201_general_sample_500_new_filtered_full_rewards_great/step-50/reward_stats.json

Batch (Epoch 1):  20%|████████▏                               | 51/250 [1:26:52<5:49:03, 105.24s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-51 >>>

Batch (Epoch 1):  21%|████████▎                               | 52/250 [1:28:24<5:34:41, 101.42s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-52 >>>

Batch (Epoch 1):  21%|████████▍                               | 53/250 [1:30:31<5:58:09, 109.09s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-53 >>>

Batch (Epoch 1):  22%|████████▋                               | 54/250 [1:32:38<6:14:15, 114.57s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-54 >>>

Batch (Epoch 1):  22%|████████▊                               | 55/250 [1:34:49<6:27:32, 119.24s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-55 >>>

Batch (Epoch 1):  22%|█████████▏                               | 56/250 [1:35:39<5:18:57, 98.64s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-56 >>>

Batch (Epoch 1):  23%|█████████                               | 57/250 [1:37:30<5:29:00, 102.28s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-57 >>>

Batch (Epoch 1):  23%|█████████▌                               | 58/250 [1:38:46<5:02:12, 94.44s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-58 >>>

Batch (Epoch 1):  24%|█████████▋                               | 59/250 [1:40:34<5:13:11, 98.39s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-59 >>>

Batch (Epoch 1):  24%|█████████▊                               | 60/250 [1:42:06<5:06:03, 96.65s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-60 >>>

Batch (Epoch 1):  24%|█████████▊                              | 61/250 [1:44:14<5:33:23, 105.84s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-61 >>>

Batch (Epoch 1):  25%|█████████▉                              | 62/250 [1:46:03<5:34:40, 106.81s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-62 >>>

Batch (Epoch 1):  25%|██████████                              | 63/250 [1:48:01<5:44:01, 110.38s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-63 >>>

Batch (Epoch 1):  26%|██████████▍                              | 64/250 [1:49:16<5:09:16, 99.77s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-64 >>>

Batch (Epoch 1):  26%|██████████▋                              | 65/250 [1:50:42<4:54:55, 95.65s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-65 >>>

Batch (Epoch 1):  26%|██████████▊                              | 66/250 [1:52:14<4:49:09, 94.29s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-66 >>>

Batch (Epoch 1):  27%|██████████▉                              | 67/250 [1:53:39<4:39:45, 91.73s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-67 >>>

Batch (Epoch 1):  27%|███████████▏                             | 68/250 [1:54:52<4:21:19, 86.15s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-68 >>>

Batch (Epoch 1):  28%|███████████▎                             | 69/250 [1:56:39<4:38:11, 92.22s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-69 >>>

Batch (Epoch 1):  28%|███████████▍                             | 70/250 [1:58:22<4:46:59, 95.67s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-70 >>>

Batch (Epoch 1):  28%|███████████▋                             | 71/250 [2:00:00<4:46:55, 96.17s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-71 >>>

Batch (Epoch 1):  29%|███████████▊                             | 72/250 [2:01:20<4:30:40, 91.24s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-72 >>>

Batch (Epoch 1):  29%|███████████▋                            | 73/250 [2:03:22<4:56:58, 100.67s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-73 >>>

Batch (Epoch 1):  30%|███████████▊                            | 74/250 [2:05:48<5:34:32, 114.05s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-74 >>>

Batch (Epoch 1):  30%|████████████                            | 75/250 [2:07:35<5:26:45, 112.03s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-75 >>>

Batch (Epoch 1):  30%|████████████▏                           | 76/250 [2:09:34<5:30:52, 114.09s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-76 >>>

Batch (Epoch 1):  31%|████████████▎                           | 77/250 [2:10:43<4:50:25, 100.72s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-77 >>>

Batch (Epoch 1):  31%|████████████▊                            | 78/250 [2:12:05<4:32:07, 94.93s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-78 >>>

Batch (Epoch 1):  32%|████████████▉                            | 79/250 [2:13:21<4:14:18, 89.23s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-79 >>>

Batch (Epoch 1):  32%|█████████████                            | 80/250 [2:15:01<4:22:24, 92.61s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-80 >>>

Batch (Epoch 1):  32%|█████████████▎                           | 81/250 [2:16:43<4:28:55, 95.48s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-81 >>>

Batch (Epoch 1):  33%|█████████████                           | 82/250 [2:18:45<4:49:17, 103.32s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-82 >>>

Batch (Epoch 1):  33%|█████████████▌                           | 83/250 [2:20:08<4:30:28, 97.18s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-83 >>>

Batch (Epoch 1):  34%|█████████████▍                          | 84/250 [2:22:09<4:48:49, 104.39s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-84 >>>

Batch (Epoch 1):  34%|█████████████▌                          | 85/250 [2:24:06<4:57:32, 108.20s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-85 >>>

Batch (Epoch 1):  34%|█████████████▊                          | 86/250 [2:26:05<5:04:32, 111.42s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-86 >>>

Batch (Epoch 1):  35%|█████████████▉                          | 87/250 [2:27:58<5:03:52, 111.85s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-87 >>>

Batch (Epoch 1):  35%|██████████████                          | 88/250 [2:30:02<5:11:53, 115.52s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-88 >>>

Batch (Epoch 1):  36%|██████████████▏                         | 89/250 [2:31:56<5:08:48, 115.08s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-89 >>>

Batch (Epoch 1):  36%|██████████████▍                         | 90/250 [2:33:26<4:47:11, 107.70s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-90 >>>

Batch (Epoch 1):  36%|██████████████▌                         | 91/250 [2:35:32<4:59:19, 112.95s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-91 >>>

Batch (Epoch 1):  37%|██████████████▋                         | 92/250 [2:37:32<5:03:08, 115.12s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-92 >>>

Batch (Epoch 1):  37%|██████████████▉                         | 93/250 [2:38:46<4:29:05, 102.83s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-93 >>>

Batch (Epoch 1):  38%|███████████████▍                         | 94/250 [2:40:00<4:05:11, 94.31s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-94 >>>

Batch (Epoch 1):  38%|███████████████▏                        | 95/250 [2:41:55<4:19:32, 100.47s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-95 >>>

Batch (Epoch 1):  38%|███████████████▋                         | 96/250 [2:43:16<4:02:38, 94.54s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-96 >>>

Batch (Epoch 1):  39%|███████████████▉                         | 97/250 [2:44:32<3:46:32, 88.84s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-97 >>>

Batch (Epoch 1):  39%|████████████████                         | 98/250 [2:46:00<3:44:33, 88.64s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-98 >>>

Batch (Epoch 1):  40%|████████████████▏                        | 99/250 [2:48:05<4:10:36, 99.58s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-99 >>>

Batch (Epoch 1):  40%|████████████████                        | 100/250 [2:49:19<3:49:35, 91.83s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-100 >>>

/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/peft/utils/save_and_load.py:154: UserWarning: Could not find a config file in ./model/Meta-Llama-3.1-8B-Instruct-GPTQ-INT4 - will assume that the vocabulary was not modified.
  warnings.warn(

>>> write to saved/lora_llama318ft_policy_r8_lr2e-07_b1_sd201_general_sample_500_new_filtered_full_rewards_great/step-100/reward_stats.json

Batch (Epoch 1):  40%|████████████████▏                       | 101/250 [2:50:43<3:42:40, 89.67s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-101 >>>

Batch (Epoch 1):  41%|████████████████▎                       | 102/250 [2:52:11<3:40:08, 89.25s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-102 >>>

Batch (Epoch 1):  41%|████████████████                       | 103/250 [2:54:26<4:11:38, 102.71s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-103 >>>

Batch (Epoch 1):  42%|████████████████▏                      | 104/250 [2:56:38<4:31:26, 111.55s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-104 >>>

Batch (Epoch 1):  42%|████████████████▍                      | 105/250 [2:58:34<4:33:00, 112.97s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-105 >>>

Batch (Epoch 1):  42%|████████████████▌                      | 106/250 [2:59:44<4:00:05, 100.04s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-106 >>>

Batch (Epoch 1):  43%|████████████████▋                      | 107/250 [3:01:36<4:06:56, 103.61s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-107 >>>

Batch (Epoch 1):  43%|████████████████▊                      | 108/250 [3:03:39<4:18:46, 109.34s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-108 >>>

Batch (Epoch 1):  44%|█████████████████▍                      | 109/250 [3:04:52<3:51:57, 98.71s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-109 >>>

Batch (Epoch 1):  44%|█████████████████▏                     | 110/250 [3:06:44<3:59:25, 102.61s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-110 >>>

Batch (Epoch 1):  44%|█████████████████▊                      | 111/250 [3:08:05<3:42:52, 96.21s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-111 >>>

Batch (Epoch 1):  45%|█████████████████▉                      | 112/250 [3:09:35<3:36:41, 94.21s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-112 >>>

Batch (Epoch 1):  45%|██████████████████                      | 113/250 [3:10:58<3:27:27, 90.85s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-113 >>>

Batch (Epoch 1):  46%|██████████████████▏                     | 114/250 [3:12:14<3:15:35, 86.29s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-114 >>>

Batch (Epoch 1):  46%|██████████████████▍                     | 115/250 [3:14:19<3:40:40, 98.07s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-115 >>>

Batch (Epoch 1):  46%|██████████████████                     | 116/250 [3:16:17<3:52:15, 104.00s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-116 >>>

Batch (Epoch 1):  47%|██████████████████▎                    | 117/250 [3:18:20<4:03:26, 109.82s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-117 >>>

Batch (Epoch 1):  47%|██████████████████▍                    | 118/250 [3:20:12<4:02:49, 110.37s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-118 >>>

Batch (Epoch 1):  48%|███████████████████                     | 119/250 [3:21:27<3:37:52, 99.79s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-119 >>>

Batch (Epoch 1):  48%|██████████████████▋                    | 120/250 [3:23:29<3:50:34, 106.42s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-120 >>>

Batch (Epoch 1):  48%|██████████████████▉                    | 121/250 [3:25:37<4:02:44, 112.91s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-121 >>>

Batch (Epoch 1):  49%|███████████████████                    | 122/250 [3:27:46<4:10:47, 117.56s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-122 >>>

Batch (Epoch 1):  49%|███████████████████▏                   | 123/250 [3:29:05<3:44:41, 106.15s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-123 >>>

Batch (Epoch 1):  50%|███████████████████▎                   | 124/250 [3:30:44<3:38:07, 103.87s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-124 >>>

Batch (Epoch 1):  50%|████████████████████                    | 125/250 [3:31:55<3:16:03, 94.11s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-125 >>>

Batch (Epoch 1):  50%|████████████████████▏                   | 126/250 [3:33:36<3:18:34, 96.09s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-126 >>>

Batch (Epoch 1):  51%|███████████████████▊                   | 127/250 [3:35:39<3:33:31, 104.16s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-127 >>>

Batch (Epoch 1):  51%|███████████████████▉                   | 128/250 [3:37:31<3:36:33, 106.50s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-128 >>>

Batch (Epoch 1):  52%|████████████████████                   | 129/250 [3:39:28<3:41:38, 109.90s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-129 >>>

Batch (Epoch 1):  52%|████████████████████▎                  | 130/250 [3:41:14<3:37:23, 108.69s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-130 >>>

Batch (Epoch 1):  52%|████████████████████▍                  | 131/250 [3:43:24<3:48:02, 114.98s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-131 >>>

Batch (Epoch 1):  53%|████████████████████▌                  | 132/250 [3:45:30<3:52:23, 118.17s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-132 >>>

Batch (Epoch 1):  53%|████████████████████▋                  | 133/250 [3:46:52<3:29:28, 107.42s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-133 >>>

Batch (Epoch 1):  54%|█████████████████████▍                  | 134/250 [3:48:12<3:11:37, 99.11s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-134 >>>

Batch (Epoch 1):  54%|█████████████████████                  | 135/250 [3:50:32<3:33:55, 111.62s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-135 >>>

Batch (Epoch 1):  54%|█████████████████████▏                 | 136/250 [3:52:28<3:34:23, 112.83s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-136 >>>

Batch (Epoch 1):  55%|█████████████████████▎                 | 137/250 [3:54:36<3:40:56, 117.31s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-137 >>>

Batch (Epoch 1):  55%|█████████████████████▌                 | 138/250 [3:56:07<3:24:28, 109.54s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-138 >>>

Batch (Epoch 1):  56%|██████████████████████▏                 | 139/250 [3:57:23<3:03:49, 99.37s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-139 >>>

Batch (Epoch 1):  56%|█████████████████████▊                 | 140/250 [3:59:06<3:04:02, 100.39s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-140 >>>

Batch (Epoch 1):  56%|█████████████████████▉                 | 141/250 [4:01:15<3:18:20, 109.18s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-141 >>>

Batch (Epoch 1):  57%|██████████████████████▏                | 142/250 [4:03:06<3:17:11, 109.55s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-142 >>>

Batch (Epoch 1):  57%|██████████████████████▎                | 143/250 [4:04:39<3:06:41, 104.68s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-143 >>>

Batch (Epoch 1):  58%|██████████████████████▍                | 144/250 [4:06:47<3:17:05, 111.56s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-144 >>>

Batch (Epoch 1):  58%|██████████████████████▌                | 145/250 [4:08:32<3:11:52, 109.64s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-145 >>>

Batch (Epoch 1):  58%|██████████████████████▊                | 146/250 [4:10:05<3:01:30, 104.71s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-146 >>>

Batch (Epoch 1):  59%|██████████████████████▉                | 147/250 [4:12:12<3:11:19, 111.46s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-147 >>>

Batch (Epoch 1):  59%|███████████████████████                | 148/250 [4:13:41<2:57:44, 104.55s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-148 >>>

Batch (Epoch 1):  60%|███████████████████████▏               | 149/250 [4:15:42<3:04:39, 109.70s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-149 >>>

Batch (Epoch 1):  60%|███████████████████████▍               | 150/250 [4:17:24<2:58:46, 107.26s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-150 >>>

/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/peft/utils/save_and_load.py:154: UserWarning: Could not find a config file in ./model/Meta-Llama-3.1-8B-Instruct-GPTQ-INT4 - will assume that the vocabulary was not modified.
  warnings.warn(

>>> write to saved/lora_llama318ft_policy_r8_lr2e-07_b1_sd201_general_sample_500_new_filtered_full_rewards_great/step-150/reward_stats.json

Batch (Epoch 1):  60%|███████████████████████▌               | 151/250 [4:19:31<3:06:56, 113.30s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-151 >>>

Batch (Epoch 1):  61%|███████████████████████▋               | 152/250 [4:20:54<2:50:05, 104.14s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-152 >>>

Batch (Epoch 1):  61%|███████████████████████▊               | 153/250 [4:22:43<2:50:39, 105.56s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-153 >>>

Batch (Epoch 1):  62%|████████████████████████▋               | 154/250 [4:24:04<2:37:09, 98.22s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-154 >>>

Batch (Epoch 1):  62%|████████████████████████▊               | 155/250 [4:25:31<2:30:04, 94.79s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-155 >>>

Batch (Epoch 1):  62%|████████████████████████▉               | 156/250 [4:27:12<2:31:31, 96.72s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-156 >>>

Batch (Epoch 1):  63%|█████████████████████████               | 157/250 [4:28:39<2:25:11, 93.68s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-157 >>>

Batch (Epoch 1):  63%|█████████████████████████▎              | 158/250 [4:30:17<2:25:39, 94.99s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-158 >>>

Batch (Epoch 1):  64%|████████████████████████▊              | 159/250 [4:32:21<2:37:09, 103.62s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-159 >>>

Batch (Epoch 1):  64%|█████████████████████████▌              | 160/250 [4:33:06<2:09:22, 86.25s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-160 >>>

Batch (Epoch 1):  64%|█████████████████████████▊              | 161/250 [4:34:34<2:08:44, 86.79s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-161 >>>

Batch (Epoch 1):  65%|█████████████████████████▉              | 162/250 [4:36:18<2:14:39, 91.81s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-162 >>>

Batch (Epoch 1):  65%|█████████████████████████▍             | 163/250 [4:38:23<2:27:41, 101.85s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-163 >>>

Batch (Epoch 1):  66%|█████████████████████████▌             | 164/250 [4:40:02<2:24:46, 101.01s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-164 >>>

Batch (Epoch 1):  66%|██████████████████████████▍             | 165/250 [4:41:26<2:16:00, 96.01s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-165 >>>

Batch (Epoch 1):  66%|██████████████████████████▌             | 166/250 [4:42:48<2:08:19, 91.66s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-166 >>>

Batch (Epoch 1):  67%|██████████████████████████             | 167/250 [4:44:58<2:22:32, 103.04s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-167 >>>

Batch (Epoch 1):  67%|██████████████████████████▉             | 168/250 [4:46:22<2:13:09, 97.43s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-168 >>>

Batch (Epoch 1):  68%|██████████████████████████▎            | 169/250 [4:48:47<2:30:44, 111.66s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-169 >>>

Batch (Epoch 1):  68%|██████████████████████████▌            | 170/250 [4:50:27<2:24:07, 108.10s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-170 >>>

Batch (Epoch 1):  68%|██████████████████████████▋            | 171/250 [4:52:29<2:27:49, 112.27s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-171 >>>

Batch (Epoch 1):  69%|██████████████████████████▊            | 172/250 [4:55:05<2:43:08, 125.50s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-172 >>>

Batch (Epoch 1):  69%|██████████████████████████▉            | 173/250 [4:56:08<2:16:50, 106.63s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-173 >>>

Batch (Epoch 1):  70%|███████████████████████████▏           | 174/250 [4:58:04<2:18:37, 109.44s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-174 >>>

Batch (Epoch 1):  70%|███████████████████████████▎           | 175/250 [5:00:06<2:21:30, 113.21s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-175 >>>

Batch (Epoch 1):  70%|███████████████████████████▍           | 176/250 [5:01:19<2:04:49, 101.21s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-176 >>>

Batch (Epoch 1):  71%|████████████████████████████▎           | 177/250 [5:02:41<1:56:10, 95.49s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-177 >>>

Batch (Epoch 1):  71%|████████████████████████████▍           | 178/250 [5:04:25<1:57:35, 97.99s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-178 >>>

Batch (Epoch 1):  72%|███████████████████████████▉           | 179/250 [5:06:36<2:07:55, 108.11s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-179 >>>

Batch (Epoch 1):  72%|████████████████████████████           | 180/250 [5:07:59<1:57:08, 100.41s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-180 >>>

Batch (Epoch 1):  72%|████████████████████████████▏          | 181/250 [5:10:00<2:02:26, 106.48s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-181 >>>

Batch (Epoch 1):  73%|█████████████████████████████           | 182/250 [5:11:13<1:49:35, 96.70s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-182 >>>

Batch (Epoch 1):  73%|████████████████████████████▌          | 183/250 [5:13:03<1:52:23, 100.64s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-183 >>>

Batch (Epoch 1):  74%|█████████████████████████████▍          | 184/250 [5:14:26<1:44:56, 95.40s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-184 >>>

Batch (Epoch 1):  74%|████████████████████████████▊          | 185/250 [5:16:31<1:52:50, 104.17s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-185 >>>

Batch (Epoch 1):  74%|█████████████████████████████          | 186/250 [5:18:21<1:52:51, 105.81s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-186 >>>

Batch (Epoch 1):  75%|█████████████████████████████▏         | 187/250 [5:20:23<1:56:24, 110.87s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-187 >>>

Batch (Epoch 1):  75%|██████████████████████████████          | 188/250 [5:21:14<1:35:54, 92.82s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-188 >>>

Batch (Epoch 1):  76%|██████████████████████████████▏         | 189/250 [5:22:37<1:31:14, 89.75s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-189 >>>

Batch (Epoch 1):  76%|██████████████████████████████▍         | 190/250 [5:24:01<1:28:07, 88.13s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-190 >>>

Batch (Epoch 1):  76%|██████████████████████████████▌         | 191/250 [5:25:19<1:23:31, 84.94s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-191 >>>

Batch (Epoch 1):  77%|██████████████████████████████▋         | 192/250 [5:26:40<1:21:09, 83.96s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-192 >>>

Batch (Epoch 1):  77%|██████████████████████████████▉         | 193/250 [5:27:58<1:18:00, 82.11s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-193 >>>

Batch (Epoch 1):  78%|███████████████████████████████         | 194/250 [5:30:08<1:29:59, 96.42s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-194 >>>

Batch (Epoch 1):  78%|███████████████████████████████▏        | 195/250 [5:31:19<1:21:33, 88.98s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-195 >>>

Batch (Epoch 1):  78%|███████████████████████████████▎        | 196/250 [5:32:49<1:20:08, 89.04s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-196 >>>

Batch (Epoch 1):  79%|███████████████████████████████▌        | 197/250 [5:34:44<1:25:32, 96.84s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-197 >>>

Batch (Epoch 1):  79%|███████████████████████████████▋        | 198/250 [5:36:09<1:20:49, 93.26s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-198 >>>

Batch (Epoch 1):  80%|███████████████████████████████▊        | 199/250 [5:37:58<1:23:25, 98.15s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-199 >>>

Batch (Epoch 1):  80%|████████████████████████████████        | 200/250 [5:39:17<1:16:51, 92.22s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-200 >>>

/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/peft/utils/save_and_load.py:154: UserWarning: Could not find a config file in ./model/Meta-Llama-3.1-8B-Instruct-GPTQ-INT4 - will assume that the vocabulary was not modified.
  warnings.warn(

>>> write to saved/lora_llama318ft_policy_r8_lr2e-07_b1_sd201_general_sample_500_new_filtered_full_rewards_great/step-200/reward_stats.json

Batch (Epoch 1):  80%|████████████████████████████████▏       | 201/250 [5:40:39<1:12:55, 89.30s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-201 >>>

Batch (Epoch 1):  81%|███████████████████████████████▌       | 202/250 [5:43:12<1:26:47, 108.49s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-202 >>>

Batch (Epoch 1):  81%|████████████████████████████████▍       | 203/250 [5:44:17<1:14:45, 95.43s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-203 >>>

Batch (Epoch 1):  82%|████████████████████████████████▋       | 204/250 [5:45:41<1:10:28, 91.92s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-204 >>>

Batch (Epoch 1):  82%|████████████████████████████████▊       | 205/250 [5:47:16<1:09:33, 92.75s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-205 >>>

Batch (Epoch 1):  82%|████████████████████████████████▏      | 206/250 [5:49:34<1:18:09, 106.58s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-206 >>>

Batch (Epoch 1):  83%|████████████████████████████████▎      | 207/250 [5:51:00<1:11:57, 100.40s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-207 >>>

Batch (Epoch 1):  83%|█████████████████████████████████▎      | 208/250 [5:52:27<1:07:18, 96.15s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-208 >>>

Batch (Epoch 1):  84%|█████████████████████████████████▍      | 209/250 [5:54:05<1:06:07, 96.78s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-209 >>>

Batch (Epoch 1):  84%|█████████████████████████████████▌      | 210/250 [5:55:52<1:06:36, 99.92s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-210 >>>

Batch (Epoch 1):  84%|████████████████████████████████▉      | 211/250 [5:57:47<1:07:51, 104.39s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-211 >>>

Batch (Epoch 1):  85%|█████████████████████████████████      | 212/250 [5:59:27<1:05:16, 103.06s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-212 >>>

Batch (Epoch 1):  85%|█████████████████████████████████▏     | 213/250 [6:01:34<1:07:57, 110.19s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-213 >>>

Batch (Epoch 1):  86%|███████████████████████████████████▉      | 214/250 [6:02:14<53:27, 89.09s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-214 >>>

Batch (Epoch 1):  86%|████████████████████████████████████      | 215/250 [6:03:58<54:35, 93.57s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-215 >>>

Batch (Epoch 1):  86%|████████████████████████████████████▎     | 216/250 [6:05:16<50:28, 89.08s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-216 >>>

Batch (Epoch 1):  87%|████████████████████████████████████▍     | 217/250 [6:07:09<52:54, 96.19s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-217 >>>

Batch (Epoch 1):  87%|████████████████████████████████████▌     | 218/250 [6:08:30<48:48, 91.53s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-218 >>>

Batch (Epoch 1):  88%|███████████████████████████████████▉     | 219/250 [6:10:41<53:27, 103.47s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-219 >>>

Batch (Epoch 1):  88%|████████████████████████████████████▉     | 220/250 [6:12:09<49:22, 98.75s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-220 >>>

Batch (Epoch 1):  88%|████████████████████████████████████▏    | 221/250 [6:14:12<51:17, 106.13s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-221 >>>

Batch (Epoch 1):  89%|█████████████████████████████████████▎    | 222/250 [6:15:29<45:23, 97.28s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-222 >>>

Batch (Epoch 1):  89%|█████████████████████████████████████▍    | 223/250 [6:17:12<44:33, 99.03s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-223 >>>

Batch (Epoch 1):  90%|█████████████████████████████████████▋    | 224/250 [6:18:39<41:25, 95.60s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-224 >>>

Batch (Epoch 1):  90%|█████████████████████████████████████▊    | 225/250 [6:20:19<40:18, 96.74s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-225 >>>

Batch (Epoch 1):  90%|█████████████████████████████████████    | 226/250 [6:22:13<40:44, 101.84s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-226 >>>

Batch (Epoch 1):  91%|█████████████████████████████████████▏   | 227/250 [6:24:23<42:22, 110.55s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-227 >>>

Batch (Epoch 1):  91%|█████████████████████████████████████▍   | 228/250 [6:26:19<41:02, 111.95s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-228 >>>

Batch (Epoch 1):  92%|█████████████████████████████████████▌   | 229/250 [6:27:47<36:41, 104.84s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-229 >>>

Batch (Epoch 1):  92%|██████████████████████████████████████▋   | 230/250 [6:29:07<32:25, 97.30s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-230 >>>

Batch (Epoch 1):  92%|██████████████████████████████████████▊   | 231/250 [6:30:29<29:22, 92.77s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-231 >>>

Batch (Epoch 1):  93%|██████████████████████████████████████▉   | 232/250 [6:31:48<26:34, 88.58s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-232 >>>

Batch (Epoch 1):  93%|███████████████████████████████████████▏  | 233/250 [6:33:52<28:06, 99.20s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-233 >>>

Batch (Epoch 1):  94%|██████████████████████████████████████▍  | 234/250 [6:35:46<27:38, 103.65s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-234 >>>

Batch (Epoch 1):  94%|██████████████████████████████████████▌  | 235/250 [6:37:50<27:26, 109.73s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-235 >>>

Batch (Epoch 1):  94%|██████████████████████████████████████▋  | 236/250 [6:39:47<26:09, 112.08s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-236 >>>

Batch (Epoch 1):  95%|██████████████████████████████████████▊  | 237/250 [6:40:59<21:41, 100.13s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-237 >>>

Batch (Epoch 1):  95%|███████████████████████████████████████  | 238/250 [6:43:04<21:30, 107.56s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-238 >>>

Batch (Epoch 1):  96%|███████████████████████████████████████▏ | 239/250 [6:44:30<18:31, 101.05s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-239 >>>

Batch (Epoch 1):  96%|████████████████████████████████████████▎ | 240/250 [6:45:46<15:35, 93.55s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-240 >>>

Batch (Epoch 1):  96%|███████████████████████████████████████▌ | 241/250 [6:47:48<15:17, 101.98s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-241 >>>

Batch (Epoch 1):  97%|████████████████████████████████████████▋ | 242/250 [6:48:59<12:22, 92.86s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-242 >>>

Batch (Epoch 1):  97%|███████████████████████████████████████▊ | 243/250 [6:51:30<12:51, 110.27s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-243 >>>

Batch (Epoch 1):  98%|████████████████████████████████████████ | 244/250 [6:53:42<11:39, 116.61s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-244 >>>

Batch (Epoch 1):  98%|████████████████████████████████████████▏| 245/250 [6:55:26<09:23, 112.79s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-245 >>>

Batch (Epoch 1):  98%|████████████████████████████████████████▎| 246/250 [6:56:57<07:05, 106.38s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-246 >>>

Batch (Epoch 1):  99%|████████████████████████████████████████▌| 247/250 [6:59:24<05:55, 118.41s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-247 >>>

Batch (Epoch 1):  99%|████████████████████████████████████████▋| 248/250 [7:00:49<03:36, 108.45s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-248 >>>

Batch (Epoch 1): 100%|████████████████████████████████████████▊| 249/250 [7:03:00<01:55, 115.18s/it]/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/an/anaconda3/envs/deep_learning_env_22/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

step-249 >>>

Batch (Epoch 1): 100%|█████████████████████████████████████████| 250/250 [7:04:55<00:00, 115.26s/it]
epoch:: 100%|████████████████████████████████████████████████████| 1/1 [7:04:55<00:00, 25495.55s/it]